import { Inter } from 'next/font/google'
// import StarsCanvas from '../components/main/StarBackground.jsx'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <StarsCanvas /> */}
        {children}
      </body>
    </html>
  )
}
